  # Weather prediction
- platform: buienradar
  name: 'Leeuwarden'
  # Force 'Meetstation Leeuwarden' to be used:
  latitude: 53.20
  longitude: 5.80
  forecast: True
- platform: pvoutput
  system_id: 36378
  api_key: !secret pv_api_key
- platform: template
  sensors:
    power_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
      friendly_name: 'Huidig opgewekt vermogen'
      unit_of_measurement: 'Watt'
    energy_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
      friendly_name: 'Opgewekt vandaag'
      unit_of_measurement: 'kWh'
