# Weather prediction
- platform: buienradar
  name: 'Leeuwarden'
  # Force 'Meetstation Leeuwarden' to be used:
  latitude: 53.20
  longitude: 5.80
  forecast: True
# PVOutput
- platform: pvoutput
  system_id: 36378
  api_key: !secret pv_api_key
- platform: template
  sensors:
    power_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "power_generation", "NaN") %}0{% else %}{{ states.sensor.pvoutput.attributes.power_generation }}{% endif %}'
      friendly_name: 'Huidig opgewekt vermogen'
      unit_of_measurement: 'Watt'
    energy_generation:
      value_template: '{% if is_state_attr("sensor.pvoutput", "energy_generation", "NaN") %}0{% else %}{{ "%0.2f"|format(states.sensor.pvoutput.attributes.energy_generation|float/1000) }}{% endif %}'
      friendly_name: 'Opgewekt vandaag'
      unit_of_measurement: 'kWh'

#Uitlezen nefit Status
- platform: mqtt
  state_topic: "nefit/status"
  name: "Temperatuur"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['in house temp']}}"
- platform: mqtt
  state_topic: "nefit/status"
  name: "Set Temp"
  device_class: temperature
  unit_of_measurement: "°C"
  value_template: "{{ value_json['temp setpoint']}}" 
- platform: mqtt
  state_topic: "nefit/status"
  name: Buitentemperatuur
  unit_of_measurement: "°C"
  value_template: "{{ value_json['outdoor temp']}}" 

#Solaredge

- platform: solaredge
  api_key: IU2879Q0R6LY3OJDREEJ7J7TZXYVYZV7
  site_id: 112167
  name: SolarEdge
- platform: template
  sensors:
    solaredge_last_year_data_template:
      value_template: '{{(states.sensor.solaredge_last_year_data.state | float / 1000) | round(2)}}'
      friendly_name: "Opbrengst huidig jaar"
      unit_of_measurement: 'KWh'